<?php
session_start();
if(isset($_SESSION["cart"])){
    array_splice($_SESSION["cart"],0);
}
?>
<script>
    window.alert("นำสินค้าออกจากตระกร้าเรียบร้อยแล้ว");
    window.location.replace("show_product.php");
</script>